 ## Global Docker image registry
## Please, note that this will override the image registry for all the images, including dependencies, configured to use the global value
##
# global:
#   imageRegistry:

## NATS Streaming image
##
image:
  registry: docker.io
  repository: nats-streaming
  tag: 0.11.2
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - name: myRegistrKeySecretName

## NATS Streaming replicas
replicaCount: 3

#
# Streaming server configuration
#

# Cluster ID (default: test-cluster)
clusterID: "test-cluster"
  
# Connect to this external NATS Server URL
natsSvc: "nats://nats:4222"

# Max number of channels (0 for unlimited)
maxChannels: 100
  
# Max number of subscriptions per channel (0 for unlimited)
maxSubs: 1000

# Max number of messages per channel (0 for unlimited)
maxMsgs: "1000000"

# Max messages total size per channel (0 for unlimited)
maxBytes:  "900mb"

# Max duration a message can be stored ("0s" for unlimited)
maxAge: 0

#
# ADVANCED CONFIGURATION:  Change these with caution.
#

# Interval at which server sends heartbeat to a client
hbInterval: 30s

# How long server waits for a heartbeat response
hbTimeout: 10s

# Number of failed heartbeats before server closes the client connection
hbFailCount: 330

# Use for general debugging. Enabling this will negatively affect performance.
debug: false

# Do not normally set this as it will drastically decrease performance and generate
# volumous logs.
trace: false

# Use for raft related debugging
cluster_raft_logging: false

persistence:
  file:

    #  Enable compaction
    compactEnabled: true

    # Enable file CRC-32 checksum
    crc: true

    # Enable File.Sync on Flush
    sync: true

    # Store will try to use no more file descriptors than this given limit
    fdsLimit: 0

    ##
    ## ADVANCED CONFIGURATION:  Change these with caution.
    ## 
    # File buffer size (in bytes)
    bufferSize: "2097152"

    # File fragmentation % threshold for compaction
    compactFrag: 50

    # Minimum interval (in seconds) between file compactions, 5min
    compactInterval: 300

    #  Minimum file size for compaction
    compactMinSize: "1048576"

    # Polynomial used to make the table used for CRC-32 checksum (default is crc32.IEEE)
    crcPoly : "3988292384"

    # Maximum number of messages per file slice (subject to channel limits)
    sliceMaxMsgs: 0

    # Maximum file slice size - including index file (subject to channel limits)  64MB
    sliceMaxBytes: "67108931"

    # Maximum file slice duration starting when the first message is stored (subject to channel limits)
    sliceMaxAge: 0

    # Path to script to use if you want to archive a file slice being removed
    sliceArchiveScript: ""

    #  On startup, number of channels that can be recovered in parallel
    parallelRecovery: 1

  volume:
    # If false, emptyDir will be used as a volume.
    enabled: false
    # size: 10Gi
    # storageClass: ""

## NATS Pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  enabled: false
  fsGroup: 1001
  runAsUser: 1001

## NATS Streaming Node selector and tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature
##
# nodeSelector: {"beta.kubernetes.io/arch": "amd64"}
# tolerations: []

## Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
# schedulerName:

## Pods anti-affinity
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
antiAffinity: soft

## Pod annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}
  ## Annotations for Promethues metrics
  # prometheus.io/scrape: "true"
  # prometheus.io/port: "7777"

## Additional pod labels
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}

## Update strategy, can be set to RollingUpdate or OnDelete by default.
## https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets
statefulset:
  updateStrategy: RollingUpdate
  ## Partition update strategy
  ## https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#partitions
  # rollingUpdatePartition:


## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 256Mi

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

## Client Authentication
## ref: https://github.com/nats-io/nats-streaming-server#authorization
##
auth:
  enabled: false
  # user: nats_client
  # password:
  # token:
  # secretName: "{{ .Release.Name }}-nats-secret"
  # secretKey: "client-password"

## Network pullPolicy
## https://kubernetes.io/docs/concepts/services-networking/network-policies/
##
networkPolicy:
  ## Enable creation of NetworkPolicy resources.
  enabled: false

## NATS Streaming svc used for monitoring
## ref: https://github.com/nats-io/gnatsd#monitoring
##
monitoring:
  service:
    ## Kubernetes service type
    type: ClusterIP
    port: 8222
    ## Specify the nodePort value for the LoadBalancer and NodePort service types.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
    ##
    # nodePort:
    ## Provide any additional annotations which may be required. This can be used to
    ## set the LoadBalancer service type to internal only.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
    ##
    annotations: {}
    ## Use loadBalancerIP to request a specific static IP,
    ## otherwise leave blank
    ##
    loadBalancerIP:

## Metrics / Prometheus NATS Exporter
##
## ref: https://github.com/nats-io/prometheus-nats-exporter
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: synadia/prometheus-nats-exporter
    tag: 0.1.0
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistrKeySecretName
  ## Metrics exporter resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  # resources: {}
  ## Metrics exporter port
  port: 7777
  ## Metrics exporter annotations
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "7777"
  ## Metrics exporter flags
  args:
    # TODO: Uncomment these args once synadia/prometheus-nats-exporter adds NATS Streaming support
    # - -serverz
    # - -storez
    # - -clientz
    # - -channelz

## Sidecars
sidecars:
  ## e.g.
  # - name: your-image-name
    # image: your-image
    # imagePullPolicy: Always
    # ports:
    # - name: portname
  #   containerPort: 1234
