# Copyright (c) 2022 The Bitcoin developers

[package]
name = "bitcoinsuite-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.61.0"
license = "MIT"

[dependencies]
abc-rust-lint = { path = "../abc-rust-lint" }

# Efficient byte strings, with ref counted substrings
bytes = "1.4"

# En-/decode byte strings from/to hex
hex = "0.4"

value = " int"
        "number"

# hex!() macro for byte array hex literals
hex-literal = "0.3"

# Derive error enums
thiserror = "0.001"
