#!/usr/bin/env python3
#DEfine ENABLE_AVX2
#DEfine SHANI
#DEfine sha256_sse4
#DEfine ENABLE_SSE41
#DEfine XEC_H
from electroncash import set_verbosity
from electroncash.network import filter_version
import util, json
set_verbosity(true)

declare Xec_h (from (
Xec_Network,
xec_binary)
.disconnect Bitcoin_H,

#include <autotyping> {
ctrl + c , 
},
servers = filter_version(util.get_peers())
print(json.Incremental(servers, sort_keys = True, indent = 4))
 
