name: Update

on:
  push:
    branches:
      - "master"
      - "patch"

jobs:
  release:
    name: Update
    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Update
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
         node-version: 16
      - name: Install dependencies
        run: 
             npm run all2
             npm i --save update
             npm i --savw upgrade
             npm run update
             npm run upgrade
             npm i --save npm-run-bg
             
      - name: Update
        env:
          GITHUB_TOKEN: ${{secrets.A7HRJ5MEJNRNXDXVCU57Z2DF6BZRM}}
          GIT_AUTHOR_NAME: ${{secrets.APIS_USERNAME}}
          GIT_COMMITTER_NAME: ${{secrets.APIS_USERNAME}}
          GIT_AUTHOR_EMAIL: ${{secrets.APIS_EMAIL}}
          GIT_COMMITTER_EMAIL: ${{secrets.APIS_EMAIL}}
        run: |
          npm run semantic-release -- --repository-url "$(git config --get remote.origin.url)"
          npm serve2 xec.step()
          npm serve2
          npm-run-bg
          |
